vistas/config/routes.rb
Vistas::Application.routes.draw do

  get 'productos' => 'products#index'

  get 'acercade' => 'homepage#aboutus'
  get 'contactanos' => 'homepage#contactus'

  root 'homepage#index'

end

vistas/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

vistas/app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

  before_action :set_page_id

  def index
  end

  def aboutus
    @current_page = 'acercade'
    @page_id = false
  end

  def contactus
  end

  private

  def set_page_id
    @page_id = 'homepage'
  end

end

vistas/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = [ {name: 'Shuco Clasico', price: 1},
                  {name: 'Shuco chorizo', price: 5},
                  {name: 'Transmetro', price: 10}
                ]

    @current_page = 'productos'
  end
end

vistas/app/helpers/application_helper.rb
module ApplicationHelper

  def navegacion
    render :partial => 'shared/navegacion'
  end

  def page_id
    @page_id ||= 'default'
  end

  def active(page, current_page = nil)
    page == current_page ? 'active' : nil
  end

end

vistas/app/helpers/homepage_helper.rb
module HomepageHelper
end

vistas/app/helpers/products_helper.rb
module ProductsHelper
end

vistas/app/views/homepage/aboutus.html.erb
<% content_for :page_title do %>
<h2>Acerca de</h2>
<% end %>



<% 5.times do  %>
<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec hendrerit tempor tellus. Donec pretium posuere tellus. Proin quam nisl, tincidunt et, mattis eget, convallis nec, purus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla posuere. Donec vitae dolor. Nullam tristique diam non turpis. Cras placerat accumsan nulla. Nullam rutrum. Nam vestibulum accumsan nisl.

</p>
<% end %>

vistas/app/views/homepage/index.html.erb
<% content_for :promo do %>
<hr />
COMA EN JOES!!!!
<hr />
<% end %>



<p>
Los mejores hotdogs de la web.
</p>

vistas/app/views/products/index.html.erb
<% content_for :page_title do %>
<h2>Nuestros Shucos</h2>
<% end %>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag    "super_shuco", media: "all",
  "data-turbolinks-track" => true %>
<% end %>



<ul class="shucos">
  <% @products.each do |product| %>
  <li class="shuco">
    <strong><%= product[:name] %></strong>
    <br />
    <%= product[:price] %>
  </li>
  <% end %>
</ul>

vistas/app/views/shared/_navegacion.html.erb
<%= link_to 'Acerca de', acercade_path, class: active('acercade', @current_page) %> |
<%= link_to 'Producto', productos_path, class: active('productos', @current_page) %> |
<%= link_to 'Contactenos', contactanos_path, class: active('contactanos', @current_page) %> |
<hr />